### PR TITLE
Move opening bracket to new line

### PR DESCRIPTION
**Pull request by datwelk**
Fixes a very minor code style inconsistency. @Caiopia @jverdi

### CODE REVIEW

**Comment by itsWill** [comment]
:shipit:

**Comment by samsiegart** [comment]
:100:

**Comment by itsWill** [comment]
please add some tests

**Comment by katdrobnjakovic** [comment]
:tophat:

**Comment by RyanBillard** [comment]
tgdxbsu

**Comment by namwen** [comment]
:8ball:

**Comment by katdrobnjakovic** [comment]
:+1: 
cg2axnr

**Comment by samsiegart** [comment]
A lot more readable this way, nice catch

**Comment by namwen** [comment]
@arka-g please review

**Comment by katdrobnjakovic** [comment]
@ohsabry thoughts?

**Comment by datwelk** [comment]
@calesennett how do you feel about this change going in? too extreme or no?

**Comment by datwelk** [comment]
cc @gmassel

**Comment by ohsabry** [comment]
:8ball:

**Comment by samsiegart** [comment]
cc @pushrax @trishume

**Comment by datwelk** [comment]
@aruzmeister @sarahschachman review please

**Comment by arka-g** [comment]
😍

**Comment by jverdi** [comment]
...speechless...

**Comment by trishume** [comment]
@samsiegart personally not a big fan of this brace style, but if it makes it consistent with the rest of the project: :ship:

**Comment by gmassel** [comment]
sorry but what the hell is going on here and why was I tagged?

**Comment by gmassel** [comment]
Guys I think we should stick to the rule book here and only use brackets to enclose information that clarifies, but is not essential to, the meaning of a sentence. Also are we sure we shouldn't be using parentheses here?

**Pull request merged**
